// <auto-generated />
// Precompiled form of CompilerHost.GenerateRuntimeSourceTail.
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

public class ListNode
{
    public int val;
    public int value;
    public ListNode? next;

    public ListNode(int val = 0, ListNode? next = null)
    {
        this.val = val;
        this.value = val;
        this.next = next;
    }
}

public class TreeNode
{
    public int val;
    public int value;
    public TreeNode? left;
    public TreeNode? right;

    public TreeNode(int val = 0, TreeNode? left = null, TreeNode? right = null)
    {
        this.val = val;
        this.value = val;
        this.left = left;
        this.right = right;
    }
}

namespace TraceCode.Internal
{
    public static class TraceCodeJsonInput
    {
        private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
        {
            PropertyNameCaseInsensitive = true,
            IncludeFields = true,
            NumberHandling = JsonNumberHandling.AllowNamedFloatingPointLiterals,
            MaxDepth = 256,
        };

        private const int MaxInputDepth = 128;
        private const int MaxInputCollectionItems = 200_000;
        private const int MaxInputObjectProperties = 50_000;
        private const int MaxInputHydrationNodes = 750_000;
        private const int MaxInputConstructorCandidates = 32;
        private const int MaxInputConstructorParameters = 32;
        private static JsonElement Root => JsonSerializer.Deserialize<JsonElement>(
            TraceCode.CSharpHost.JudgeRuntimeContext.GetCurrentInputsJson(),
            JsonOptions
        );

        private static string[] Keys => Root.ValueKind == JsonValueKind.Object
            ? Root.EnumerateObject().Select(property => property.Name).ToArray()
            : Array.Empty<string>();

        public static T? Read<T>(string name, int index)
        {
            if (Root.ValueKind != JsonValueKind.Object)
            {
                throw new InvalidOperationException("TraceCode C# inputs must be a JSON object.");
            }

            if (Root.TryGetProperty(name, out JsonElement namedValue))
            {
                return ReadValue<T>(namedValue);
            }

            if (index >= 0 && index < Keys.Length && Root.TryGetProperty(Keys[index], out JsonElement indexedValue))
            {
                return ReadValue<T>(indexedValue);
            }

            throw new InvalidOperationException($"Missing input value for parameter \"{name}\".");
        }

        public static bool Has(string name, int index)
        {
            if (Root.ValueKind != JsonValueKind.Object)
            {
                throw new InvalidOperationException("TraceCode C# inputs must be a JSON object.");
            }

            if (Root.TryGetProperty(name, out _))
            {
                return true;
            }

            return index >= 0 && index < Keys.Length && Root.TryGetProperty(Keys[index], out _);
        }

        public static object? Convert(JsonElement value, Type targetType)
        {
            InputHydrationBudget budget = new();
            if (targetType == typeof(ListNode))
            {
                return ReadListNode(value, new Dictionary<string, ListNode>(StringComparer.Ordinal), budget, 0);
            }

            if (targetType == typeof(TreeNode))
            {
                return ReadTreeNode(value, new Dictionary<string, TreeNode>(StringComparer.Ordinal), budget, 0);
            }

            if (targetType == typeof(object[]))
            {
                return ReadObjectArray(value, budget, 0);
            }

            if (targetType == typeof(object[][]))
            {
                return ReadObjectMatrix(value, budget, 0);
            }

            if (targetType == typeof(object))
            {
                return ReadObjectValue(value, budget, 0);
            }

            if (TryReadObjectValueDictionary(value, targetType, budget, 0, out object? objectValueDictionary))
            {
                return objectValueDictionary;
            }

            RejectUnsafeFrameworkObjectInput(value, targetType);

            if (ShouldUseStructuredObjectReader(value, targetType))
            {
                return ReadStructuredValue(value, targetType, new Dictionary<string, object>(StringComparer.Ordinal), budget, 0);
            }

            return JsonSerializer.Deserialize(value.GetRawText(), targetType, JsonOptions);
        }

        private static T? ReadValue<T>(JsonElement value)
        {
            InputHydrationBudget budget = new();
            if (typeof(T) == typeof(ListNode))
            {
                return (T?)(object?)ReadListNode(value, new Dictionary<string, ListNode>(StringComparer.Ordinal), budget, 0);
            }

            if (typeof(T) == typeof(TreeNode))
            {
                return (T?)(object?)ReadTreeNode(value, new Dictionary<string, TreeNode>(StringComparer.Ordinal), budget, 0);
            }

            if (typeof(T) == typeof(object[]))
            {
                return (T?)(object?)ReadObjectArray(value, budget, 0);
            }

            if (typeof(T) == typeof(object[][]))
            {
                return (T?)(object?)ReadObjectMatrix(value, budget, 0);
            }

            if (typeof(T) == typeof(object))
            {
                return (T?)ReadObjectValue(value, budget, 0);
            }

            if (TryReadObjectValueDictionary(value, typeof(T), budget, 0, out object? objectValueDictionary))
            {
                return (T?)objectValueDictionary;
            }

            RejectUnsafeFrameworkObjectInput(value, typeof(T));

            if (ShouldUseStructuredObjectReader(value, typeof(T)))
            {
                return (T?)ReadStructuredValue(value, typeof(T), new Dictionary<string, object>(StringComparer.Ordinal), budget, 0);
            }

            return JsonSerializer.Deserialize<T>(value.GetRawText(), JsonOptions);
        }

        private static bool ShouldUseStructuredObjectReader(JsonElement value, Type targetType)
        {
            Type effectiveType = Nullable.GetUnderlyingType(targetType) ?? targetType;
            if (value.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined)
            {
                return false;
            }

            if (effectiveType == typeof(string)
                || effectiveType.IsPrimitive
                || effectiveType.IsEnum
                || effectiveType == typeof(decimal)
                || effectiveType == typeof(DateTime)
                || effectiveType == typeof(JsonElement)
                || IsSupportedDictionaryType(effectiveType))
            {
                return false;
            }

            return value.ValueKind == JsonValueKind.Object
                || value.ValueKind == JsonValueKind.Array && IsSupportedStructuredSequenceType(effectiveType);
        }

        private static void RejectUnsafeFrameworkObjectInput(JsonElement value, Type targetType)
        {
            Type effectiveType = Nullable.GetUnderlyingType(targetType) ?? targetType;
            if (value.ValueKind != JsonValueKind.Object
                || effectiveType == typeof(object)
                || effectiveType == typeof(JsonElement)
                || IsSupportedDictionaryType(effectiveType)
                || !IsFrameworkInputHydrationType(effectiveType))
            {
                return;
            }

            throw new InvalidOperationException($"C# input hydration does not support object-shaped JSON for framework type {effectiveType.FullName}.");
        }

        private static bool IsFrameworkInputHydrationType(Type targetType)
        {
            if (targetType.IsArray)
            {
                return false;
            }

            string? ns = targetType.Namespace;
            return ns is not null && ns.StartsWith("System", StringComparison.Ordinal);
        }

        private static bool IsSupportedStructuredSequenceType(Type targetType)
        {
            if (targetType.IsArray)
            {
                return true;
            }

            return targetType.IsGenericType
                && targetType.GetGenericTypeDefinition() == typeof(List<>);
        }

        private static object? ReadStructuredValue(JsonElement value, Type targetType, IDictionary<string, object> refs, InputHydrationBudget budget, int depth)
        {
            budget.EnterNode(depth);
            Type effectiveType = Nullable.GetUnderlyingType(targetType) ?? targetType;
            if (value.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined)
            {
                return null;
            }

            if (effectiveType == typeof(JsonElement))
            {
                return value;
            }

            if (effectiveType == typeof(string))
            {
                return value.GetString();
            }

            if (effectiveType == typeof(object))
            {
                return ReadObjectValue(value, budget, depth);
            }

            if (effectiveType.IsPrimitive || effectiveType.IsEnum || effectiveType == typeof(decimal))
            {
                return JsonSerializer.Deserialize(value.GetRawText(), effectiveType, JsonOptions);
            }

            if (IsSupportedDictionaryType(effectiveType))
            {
                if (TryReadObjectValueDictionary(value, effectiveType, budget, depth, out object? objectValueDictionary))
                {
                    return objectValueDictionary;
                }

                return JsonSerializer.Deserialize(value.GetRawText(), effectiveType, JsonOptions);
            }

            RejectUnsafeFrameworkObjectInput(value, effectiveType);

            if (effectiveType.IsArray)
            {
                Type elementType = effectiveType.GetElementType() ?? typeof(object);
                JsonElement[] values = ReadInputArrayItems(value, budget, "C# input array");
                Array array = Array.CreateInstance(elementType, values.Length);
                for (int i = 0; i < values.Length; i++)
                {
                    array.SetValue(ReadStructuredValue(values[i], elementType, refs, budget, depth + 1), i);
                }
                return array;
            }

            if (effectiveType.IsGenericType && effectiveType.GetGenericTypeDefinition() == typeof(List<>))
            {
                Type elementType = effectiveType.GetGenericArguments()[0];
                System.Collections.IList list = (System.Collections.IList)Activator.CreateInstance(effectiveType)!;
                foreach (JsonElement item in ReadInputArrayItems(value, budget, "C# input list"))
                {
                    list.Add(ReadStructuredValue(item, elementType, refs, budget, depth + 1));
                }
                return list;
            }

            if (value.ValueKind != JsonValueKind.Object)
            {
                return JsonSerializer.Deserialize(value.GetRawText(), effectiveType, JsonOptions);
            }

            if (TryReadStringProperty(value, "__ref__", out string? refId))
            {
                return refs.TryGetValue(refId, out object? referenced)
                    ? referenced
                    : throw new InvalidOperationException($"Unknown object reference \"{refId}\".");
            }

            GuardInputObjectPropertyCount(value, budget, "C# input object");
            object instance = CreateStructuredObject(value, effectiveType, refs, budget, depth);
            if (TryReadStringProperty(value, "__id__", out string? id))
            {
                refs[id] = instance;
            }

            foreach (FieldInfo field in effectiveType.GetFields(BindingFlags.Public | BindingFlags.Instance))
            {
                if (TryGetProperty(value, field.Name, out JsonElement property))
                {
                    field.SetValue(instance, ReadStructuredValue(property, field.FieldType, refs, budget, depth + 1));
                }
            }

            foreach (PropertyInfo property in effectiveType.GetProperties(BindingFlags.Public | BindingFlags.Instance))
            {
                if (!property.CanWrite
                    || property.GetIndexParameters().Length > 0
                    || !TryGetProperty(value, property.Name, out JsonElement propertyValue))
                {
                    continue;
                }

                property.SetValue(instance, ReadStructuredValue(propertyValue, property.PropertyType, refs, budget, depth + 1));
            }

            return instance;
        }

        private static bool IsSupportedDictionaryType(Type type)
        {
            return TryGetSupportedDictionaryTypes(type, out _, out _);
        }

        private static bool TryGetSupportedDictionaryTypes(Type type, out Type keyType, out Type valueType)
        {
            if (type.IsGenericType && IsDictionaryGenericType(type.GetGenericTypeDefinition()))
            {
                Type[] args = type.GetGenericArguments();
                keyType = args[0];
                valueType = args[1];
                return true;
            }

            Type? interfaceType = type
                .GetInterfaces()
                .FirstOrDefault(candidate => candidate.IsGenericType && IsDictionaryGenericType(candidate.GetGenericTypeDefinition()));
            if (interfaceType is not null)
            {
                Type[] args = interfaceType.GetGenericArguments();
                keyType = args[0];
                valueType = args[1];
                return true;
            }

            keyType = typeof(object);
            valueType = typeof(object);
            return false;
        }

        private static bool IsDictionaryGenericType(Type type)
        {
            return type == typeof(Dictionary<,>)
                || type == typeof(IDictionary<,>)
                || type == typeof(IReadOnlyDictionary<,>);
        }

        private static bool TryReadObjectValueDictionary(JsonElement value, Type targetType, InputHydrationBudget budget, int depth, out object? dictionary)
        {
            Type effectiveType = Nullable.GetUnderlyingType(targetType) ?? targetType;
            if (value.ValueKind != JsonValueKind.Object
                || !TryGetSupportedDictionaryTypes(effectiveType, out Type keyType, out Type valueType)
                || valueType != typeof(object))
            {
                dictionary = null;
                return false;
            }

            Type dictionaryType = effectiveType.IsInterface || effectiveType.IsAbstract
                ? typeof(Dictionary<,>).MakeGenericType(keyType, typeof(object))
                : effectiveType;
            Type mutableDictionaryType = typeof(IDictionary<,>).MakeGenericType(keyType, typeof(object));
            if (!mutableDictionaryType.IsAssignableFrom(dictionaryType))
            {
                dictionary = null;
                return false;
            }

            object result = Activator.CreateInstance(dictionaryType)!;
            System.Reflection.MethodInfo addMethod = mutableDictionaryType.GetMethod("Add", new[] { keyType, typeof(object) })
                ?? throw new InvalidOperationException("Unable to resolve dictionary Add method.");
            GuardInputObjectPropertyCount(value, budget, "C# input dictionary");
            foreach (JsonProperty property in value.EnumerateObject())
            {
                addMethod.Invoke(result, new[] { ReadDictionaryKey(property.Name, keyType), ReadObjectValue(property.Value, budget, depth + 1) });
            }

            dictionary = result;
            return true;
        }

        private static object ReadDictionaryKey(string key, Type keyType)
        {
            if (keyType == typeof(string) || keyType == typeof(object))
            {
                return key;
            }

            if (keyType.IsEnum)
            {
                return Enum.Parse(keyType, key, ignoreCase: true);
            }

            return System.Convert.ChangeType(key, keyType, System.Globalization.CultureInfo.InvariantCulture);
        }

        private static object CreateStructuredObject(JsonElement value, Type targetType, IDictionary<string, object> refs, InputHydrationBudget budget, int depth)
        {
            ConstructorInfo? parameterless = targetType.GetConstructor(Type.EmptyTypes);
            if (parameterless is not null)
            {
                return parameterless.Invoke(null);
            }

            int constructorIndex = 0;
            foreach (ConstructorInfo constructor in targetType
                .GetConstructors(BindingFlags.Public | BindingFlags.Instance)
                .OrderByDescending(candidate => candidate.GetParameters().Length))
            {
                budget.RecordConstructorCandidate(constructorIndex++, targetType.FullName ?? targetType.Name);
                ParameterInfo[] parameters = constructor.GetParameters();
                budget.RecordConstructorParameterCount(parameters.Length, targetType.FullName ?? targetType.Name);
                if (!parameters.All(IsSafeInputConstructorParameter))
                {
                    continue;
                }

                if (!parameters.All(parameter => TryGetProperty(value, parameter.Name ?? string.Empty, out _) || parameter.HasDefaultValue))
                {
                    continue;
                }

                object?[] args = parameters.Select(parameter =>
                    TryGetProperty(value, parameter.Name ?? string.Empty, out JsonElement property)
                        ? ReadStructuredValue(property, parameter.ParameterType, refs, budget, depth + 1)
                        : parameter.DefaultValue
                ).ToArray();
                return constructor.Invoke(args);
            }

            if (targetType.IsValueType)
            {
                return Activator.CreateInstance(targetType)!;
            }

            throw new InvalidOperationException($"Cannot hydrate input object of type {targetType.FullName}.");
        }

        private static bool IsSafeInputConstructorParameter(ParameterInfo parameter)
        {
            Type parameterType = parameter.ParameterType;
            return !parameter.IsOut
                && !parameterType.IsByRef
                && !parameterType.IsPointer
                && parameterType != typeof(IntPtr)
                && parameterType != typeof(UIntPtr)
                && !typeof(Delegate).IsAssignableFrom(parameterType);
        }

        private static object[][] ReadObjectMatrix(JsonElement value, InputHydrationBudget budget, int depth)
        {
            budget.EnterNode(depth);
            JsonElement[] rows = ReadInputArrayItems(value, budget, "C# input object matrix");
            object[][] matrix = new object[rows.Length][];
            for (int i = 0; i < rows.Length; i++)
            {
                matrix[i] = ReadObjectArray(rows[i], budget, depth + 1);
            }
            return matrix;
        }

        private static object[] ReadObjectArray(JsonElement value, InputHydrationBudget budget, int depth)
        {
            budget.EnterNode(depth);
            JsonElement[] values = ReadInputArrayItems(value, budget, "C# input array");
            object[] result = new object[values.Length];
            for (int i = 0; i < values.Length; i++)
            {
                result[i] = ReadObjectValue(values[i], budget, depth + 1);
            }
            return result;
        }

        private static object? ReadObjectValue(JsonElement value, InputHydrationBudget budget, int depth)
        {
            budget.EnterNode(depth);
            return value.ValueKind switch
            {
                JsonValueKind.String => value.GetString(),
                JsonValueKind.Number => ReadObjectNumber(value),
                JsonValueKind.True => true,
                JsonValueKind.False => false,
                JsonValueKind.Null or JsonValueKind.Undefined => null,
                JsonValueKind.Array => ReadObjectArray(value, budget, depth),
                JsonValueKind.Object => ReadObjectDictionary(value, budget, depth),
                _ => null,
            };
        }

        private static Dictionary<string, object?> ReadObjectDictionary(JsonElement value, InputHydrationBudget budget, int depth)
        {
            GuardInputObjectPropertyCount(value, budget, "C# input object");
            Dictionary<string, object?> result = new(StringComparer.Ordinal);
            foreach (JsonProperty property in value.EnumerateObject())
            {
                result[property.Name] = ReadObjectValue(property.Value, budget, depth + 1);
            }
            return result;
        }

        private static object ReadObjectNumber(JsonElement value)
        {
            if (value.TryGetInt32(out int intValue))
            {
                return intValue;
            }

            if (value.TryGetInt64(out long longValue))
            {
                return longValue;
            }

            double doubleValue = value.GetDouble();
            if (double.IsFinite(doubleValue) && Math.Truncate(doubleValue) == doubleValue)
            {
                if (doubleValue >= int.MinValue && doubleValue <= int.MaxValue)
                {
                    return (int)doubleValue;
                }

                if (doubleValue >= long.MinValue && doubleValue <= long.MaxValue)
                {
                    return (long)doubleValue;
                }
            }

            return doubleValue;
        }

        private static ListNode? ReadListNode(JsonElement value, IDictionary<string, ListNode> refs, InputHydrationBudget budget, int depth)
        {
            budget.EnterNode(depth);
            if (value.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined)
            {
                return null;
            }

            if (value.ValueKind == JsonValueKind.Array)
            {
                ListNode? head = null;
                ListNode? cursor = null;
                foreach (JsonElement item in ReadInputArrayItems(value, budget, "C# ListNode input array"))
                {
                    budget.EnterNode(depth + 1);
                    if (item.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined)
                    {
                        continue;
                    }

                    ListNode node = new(item.GetInt32());
                    if (head is null)
                    {
                        head = node;
                    }
                    else
                    {
                        cursor!.next = node;
                    }

                    cursor = node;
                }

                return head;
            }

            if (value.ValueKind == JsonValueKind.Object)
            {
                GuardInputObjectPropertyCount(value, budget, "C# ListNode input object");
                if (TryReadStringProperty(value, "__ref__", out string? refId))
                {
                    return refs.TryGetValue(refId, out ListNode? referenced)
                        ? referenced
                        : throw new InvalidOperationException($"Unknown ListNode reference \"{refId}\".");
                }

                int nodeValue = ReadIntProperty(value, "val", "value");
                ListNode node = new(nodeValue);
                if (TryReadStringProperty(value, "__id__", out string? id))
                {
                    refs[id] = node;
                }

                if (TryGetProperty(value, "next", out JsonElement next))
                {
                    node.next = ReadListNode(next, refs, budget, depth + 1);
                }

                return node;
            }

            return new ListNode(value.GetInt32());
        }

        private static TreeNode? ReadTreeNode(JsonElement value, IDictionary<string, TreeNode> refs, InputHydrationBudget budget, int depth)
        {
            budget.EnterNode(depth);
            if (value.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined)
            {
                return null;
            }

            if (value.ValueKind == JsonValueKind.Array)
            {
                JsonElement[] values = ReadInputArrayItems(value, budget, "C# TreeNode input array");
                if (values.Length == 0 || values[0].ValueKind is JsonValueKind.Null or JsonValueKind.Undefined)
                {
                    return null;
                }

                TreeNode root = new(values[0].GetInt32());
                Queue<TreeNode> queue = new();
                queue.Enqueue(root);
                int cursor = 1;

                while (queue.Count > 0 && cursor < values.Length)
                {
                    TreeNode parent = queue.Dequeue();

                    if (cursor < values.Length && values[cursor].ValueKind is not JsonValueKind.Null and not JsonValueKind.Undefined)
                    {
                        parent.left = new TreeNode(values[cursor].GetInt32());
                        queue.Enqueue(parent.left);
                    }
                    cursor++;

                    if (cursor < values.Length && values[cursor].ValueKind is not JsonValueKind.Null and not JsonValueKind.Undefined)
                    {
                        parent.right = new TreeNode(values[cursor].GetInt32());
                        queue.Enqueue(parent.right);
                    }
                    cursor++;
                }

                return root;
            }

            if (value.ValueKind == JsonValueKind.Object)
            {
                GuardInputObjectPropertyCount(value, budget, "C# TreeNode input object");
                if (TryReadStringProperty(value, "__ref__", out string? refId))
                {
                    return refs.TryGetValue(refId, out TreeNode? referenced)
                        ? referenced
                        : throw new InvalidOperationException($"Unknown TreeNode reference \"{refId}\".");
                }

                TreeNode node = new(ReadIntProperty(value, "val", "value"));
                if (TryReadStringProperty(value, "__id__", out string? id))
                {
                    refs[id] = node;
                }

                if (TryGetProperty(value, "left", out JsonElement left))
                {
                    node.left = ReadTreeNode(left, refs, budget, depth + 1);
                }

                if (TryGetProperty(value, "right", out JsonElement right))
                {
                    node.right = ReadTreeNode(right, refs, budget, depth + 1);
                }

                return node;
            }

            return new TreeNode(value.GetInt32());
        }

        private static JsonElement[] ReadInputArrayItems(JsonElement value, InputHydrationBudget budget, string label)
        {
            List<JsonElement> items = new();
            int index = 0;
            foreach (JsonElement item in value.EnumerateArray())
            {
                budget.RecordCollectionItem(index++, label);
                items.Add(item);
            }
            return items.ToArray();
        }

        private static void GuardInputObjectPropertyCount(JsonElement value, InputHydrationBudget budget, string label)
        {
            int index = 0;
            foreach (JsonProperty _ in value.EnumerateObject())
            {
                budget.RecordObjectProperty(index++, label);
            }
        }

        private sealed class InputHydrationBudget
        {
            private int nodes;

            public void EnterNode(int depth)
            {
                if (depth > MaxInputDepth)
                {
                    throw new InvalidOperationException($"C# input exceeds maximum depth of {MaxInputDepth}.");
                }

                nodes++;
                if (nodes > MaxInputHydrationNodes)
                {
                    throw new InvalidOperationException($"C# input hydration exceeds maximum JSON value count of {MaxInputHydrationNodes}.");
                }
            }

            public void RecordCollectionItem(int index, string label)
            {
                if (index >= MaxInputCollectionItems)
                {
                    throw new InvalidOperationException($"{label} exceeds maximum item count of {MaxInputCollectionItems}.");
                }
            }

            public void RecordObjectProperty(int index, string label)
            {
                if (index >= MaxInputObjectProperties)
                {
                    throw new InvalidOperationException($"{label} exceeds maximum property count of {MaxInputObjectProperties}.");
                }
            }

            public void RecordConstructorCandidate(int index, string label)
            {
                if (index >= MaxInputConstructorCandidates)
                {
                    throw new InvalidOperationException($"{label} exceeds maximum constructor candidate count of {MaxInputConstructorCandidates}.");
                }
            }

            public void RecordConstructorParameterCount(int count, string label)
            {
                if (count > MaxInputConstructorParameters)
                {
                    throw new InvalidOperationException($"{label} constructor exceeds maximum parameter count of {MaxInputConstructorParameters}.");
                }
            }
        }

        private static bool TryGetProperty(JsonElement value, string name, out JsonElement property)
        {
            foreach (JsonProperty candidate in value.EnumerateObject())
            {
                if (string.Equals(candidate.Name, name, StringComparison.OrdinalIgnoreCase))
                {
                    property = candidate.Value;
                    return true;
                }
            }

            property = default;
            return false;
        }

        private static bool TryReadStringProperty(JsonElement value, string name, out string? text)
        {
            if (TryGetProperty(value, name, out JsonElement property)
                && property.ValueKind == JsonValueKind.String)
            {
                text = property.GetString();
                return !string.IsNullOrEmpty(text);
            }

            text = null;
            return false;
        }

        private static int ReadIntProperty(JsonElement value, string primaryName, string fallbackName)
        {
            if (TryGetProperty(value, primaryName, out JsonElement primary) && primary.ValueKind == JsonValueKind.Number)
            {
                return primary.GetInt32();
            }

            if (TryGetProperty(value, fallbackName, out JsonElement fallback) && fallback.ValueKind == JsonValueKind.Number)
            {
                return fallback.GetInt32();
            }

            return 0;
        }
    }

    public static class TraceCodeTrace
    {
        public static void Line(int line, string? function)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Line(line, function);
        }

        public static void Call(string function, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Call(function, line);
        }

        public static void Call(string function, int line, IReadOnlyList<object?> args)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Call(function, line, args);
        }

        public static void Call(string function, int line, IReadOnlyDictionary<string, object?> args)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Call(function, line, args);
        }

        public static void Return(string function, int line, object? value = null)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Return(function, line, value);
        }

        public static void Leave(string function)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Leave(function);
        }

        public static void Exception(int line, string? message)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Exception(line, message);
        }

        public static void Write(string variable, object? value, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Write(variable, value, line);
        }

        public static void Read(string variable, object? value, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Read(variable, value, line);
        }

        public static void Snapshot(string variable, object? value, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, value, line);
        }

        public static void SetCurrentLine(int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.SetCurrentLine(line);
        }

        public static void WithSourceLine(int line, Action action)
        {
            int previousLine = TraceCode.CSharpHost.RuntimeTraceSink.CurrentLine;
            int previousScopedLine = TraceCode.CSharpHost.RuntimeTraceSink.CurrentScopedSourceLine;
            TraceCode.CSharpHost.RuntimeTraceSink.Line(line, TraceCode.CSharpHost.RuntimeTraceSink.CurrentFunction);
            TraceCode.CSharpHost.RuntimeTraceSink.SetCurrentLine(line);
            TraceCode.CSharpHost.RuntimeTraceSink.SetScopedSourceLine(line);
            try
            {
                action();
            }
            finally
            {
                TraceCode.CSharpHost.RuntimeTraceSink.SetScopedSourceLine(previousScopedLine);
                TraceCode.CSharpHost.RuntimeTraceSink.SetCurrentLine(previousLine);
            }
        }

        public static void CollectionMutationCall(int line, string variable, string method, IReadOnlyList<object?> args, Action action)
        {
            int startIndex = TraceCode.CSharpHost.RuntimeTraceSink.EventCount;
            WithSourceLine(line, action);
            if (!TraceCode.CSharpHost.RuntimeTraceSink.HasMutationSince(startIndex, variable, method, line))
            {
                TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, method, args, line);
            }
        }

        public static void CollectionMutationCall(int line, string variable, string method, IReadOnlyList<object?> args, Action action, object? collection)
        {
            int startIndex = TraceCode.CSharpHost.RuntimeTraceSink.EventCount;
            WithSourceLine(line, action);
            if (TraceCode.CSharpHost.RuntimeTraceSink.HasMutationSince(startIndex, variable, method, line))
            {
                return;
            }

            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, method, args, line);
            TraceCode.CSharpHost.RuntimeTraceSink.Write(variable, collection, line);
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedBulkWrite(variable, collection, line);
        }

        public static void FieldCollectionMutationCall(int line, string variable, string[] path, string method, IReadOnlyList<object?> args, Action action, object? collection)
        {
            int startIndex = TraceCode.CSharpHost.RuntimeTraceSink.EventCount;
            WithSourceLine(line, action);
            if (TraceCode.CSharpHost.RuntimeTraceSink.HasMutationSince(startIndex, variable, path, method, line))
            {
                return;
            }
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, path, method, args, line);
            TraceCode.CSharpHost.RuntimeTraceSink.FieldWrite(variable, path, collection, line);
            EmitFieldIndexedWrites(variable, path, collection, line);
        }

        private static void EmitFieldIndexedWrites(string variable, string[] path, object? collection, int line)
        {
            if (collection is string || collection is not System.Collections.IEnumerable enumerable)
            {
                return;
            }

            int index = 0;
            int limit = TraceCode.CSharpHost.RuntimeTraceSink.BulkIndexedWriteLimit(collection is System.Collections.ICollection collectionWithCount
                ? collectionWithCount.Count
                : int.MaxValue);
            foreach (object? item in enumerable)
            {
                if (index >= limit)
                {
                    break;
                }
                object?[] indexedPath = new object?[path.Length + 1];
                for (int pathIndex = 0; pathIndex < path.Length; pathIndex += 1)
                {
                    indexedPath[pathIndex] = path[pathIndex];
                }
                indexedPath[path.Length] = index;
                TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, indexedPath, item, line);
                index += 1;
            }
        }

        public static bool LoopCondition(int line, string? function, Func<bool> action)
        {
            return WithSourceLine(line, action);
        }

        public static bool LoopCondition(int line, string? function, Func<bool> action, Action snapshot)
        {
            bool result = WithSourceLine(line, action);
            snapshot();
            return result;
        }

        public static IEnumerable<T> EnumerableSource<T>(int line, string? function, Func<IEnumerable<T>> action)
        {
            return WithSourceLine(line, action);
        }

        public static IEnumerable<T> EnumerableSource<T>(int line, string? function, Func<IEnumerable<T>> action, Action snapshot)
        {
            IEnumerable<T> result = WithSourceLine(line, action);
            snapshot();
            return result;
        }

        public static T WithSourceLine<T>(int line, Func<T> action)
        {
            int previousLine = TraceCode.CSharpHost.RuntimeTraceSink.CurrentLine;
            int previousScopedLine = TraceCode.CSharpHost.RuntimeTraceSink.CurrentScopedSourceLine;
            TraceCode.CSharpHost.RuntimeTraceSink.Line(line, TraceCode.CSharpHost.RuntimeTraceSink.CurrentFunction);
            TraceCode.CSharpHost.RuntimeTraceSink.SetCurrentLine(line);
            TraceCode.CSharpHost.RuntimeTraceSink.SetScopedSourceLine(line);
            try
            {
                return action();
            }
            finally
            {
                TraceCode.CSharpHost.RuntimeTraceSink.SetScopedSourceLine(previousScopedLine);
                TraceCode.CSharpHost.RuntimeTraceSink.SetCurrentLine(previousLine);
            }
        }

        public static void Mutate(string variable, string method, IReadOnlyList<object?> args)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, method, args);
        }

        public static void Mutate(string variable, string method, IReadOnlyList<object?> args, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, method, args, line);
        }

        public static void Mutate(string variable, object index, string method, IReadOnlyList<object?> args)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, new object?[] { index }, method, args);
        }

        public static void Mutate(string variable, object index, string method, IReadOnlyList<object?> args, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, new object?[] { index }, method, args, line);
        }

        public static void Mutate(string variable, object index, string method, IReadOnlyList<object?> args, int line, IReadOnlyList<string?>? indexSources)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, new object?[] { index }, method, args, line, indexSources);
        }

        public static void Mutate(string variable, string[] path, string method, IReadOnlyList<object?> args)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, path, method, args);
        }

        public static void Mutate(string variable, string[] path, string method, IReadOnlyList<object?> args, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, path, method, args, line);
        }

        public static void Mutate(string variable, object?[] path, string method, IReadOnlyList<object?> args)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, path, method, args);
        }

        public static void Mutate(string variable, object?[] path, string method, IReadOnlyList<object?> args, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, path, method, args, line);
        }

        public static void Mutate(string variable, object?[] path, string method, IReadOnlyList<object?> args, int line, IReadOnlyList<string?>? indexSources)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, path, method, args, line, indexSources);
        }

        public static void IndexedRead(string variable, object index, object? value, int line, IReadOnlyList<string?>? indexSources = null)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, index, value, line, null, indexSources);
        }

        public static T IndexedRead<T>(string variable, object?[] path, T value, int line, IReadOnlyList<string?>? indexSources = null)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, path, value, line, null, indexSources);
            return value;
        }

        public static bool ContainsRead(bool contains, string variable, object? key, int line, IReadOnlyList<string?>? indexSources = null)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, key!, contains, line, null, indexSources);
            return contains;
        }

        public static bool ContainsRead(bool contains, string variable, object?[] path, int line, IReadOnlyList<string?>? indexSources = null)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, path, contains, line, null, indexSources);
            return contains;
        }

        public static T ArrayRead<T>(T[] array, int index, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            T value = array[index];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, index, value, line, null, indexSources);
            return value;
        }

        public static T[] ArraySliceRead<T>(T[] array, Range range, object?[] path, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            T[] value = array[range];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, path, value, line, null, indexSources);
            return value;
        }

        public static T[] ArraySliceRead<T>(T[] array, Range range, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            T[] value = array[range];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, ArraySlicePath(array.Length, range), value, line, null, indexSources);
            return value;
        }

        private static object?[] ArraySlicePath(int length, Range range)
        {
            return new object?[] { range.Start.GetOffset(length), range.End.GetOffset(length) };
        }

        public static T ArrayRead<T>(IList<T> list, int index, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            T value = list[index];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, index, value, line, null, indexSources);
            return value;
        }

        public static TValue ArrayRead<TKey, TValue>(IDictionary<TKey, TValue> dictionary, TKey key, string variable, int line, IReadOnlyList<string?>? indexSources = null)
            where TKey : notnull
        {
            TValue value = dictionary[key];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, key, value, line, null, indexSources);
            return value;
        }

        public static TValue ArrayRead<TKey, TValue>(
            IDictionary<TKey, TValue[]> dictionary,
            TKey key,
            int index,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            TValue value = dictionary[key][index];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { key, index }, value, line, null, indexSources);
            return value;
        }

        public static TValue ArrayRead<TKey, TValue>(
            IDictionary<TKey, List<TValue>> dictionary,
            TKey key,
            int index,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            TValue value = dictionary[key][index];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { key, index }, value, line, null, indexSources);
            return value;
        }

        public static TValue ArrayRead<TKey, TValue>(
            IDictionary<TKey, TraceCodeList<TValue>> dictionary,
            TKey key,
            int index,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            TValue value = dictionary[key][index];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { key, index }, value, line, null, indexSources);
            return value;
        }

        public static char ArrayRead<TKey>(IDictionary<TKey, string> dictionary, TKey key, int index, string variable, int line, IReadOnlyList<string?>? indexSources = null)
            where TKey : notnull
        {
            char value = dictionary[key][index];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { key, index }, value, line, null, indexSources);
            return value;
        }

        public static T ArrayRead<T>(T[][] array, int row, int column, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            T value = array[row][column];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, column }, value, line, null, indexSources);
            return value;
        }

        public static T ArrayRead<T>(T[,] array, int row, int column, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            T value = array[row, column];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, column }, value, line, null, indexSources);
            return value;
        }

        public static T ArrayRead<T>(T[,,] array, int first, int second, int third, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            T value = array[first, second, third];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { first, second, third }, value, line, null, indexSources);
            return value;
        }

        public static T ArrayRead<T>(TraceCodeList<T[]> list, int row, int column, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            T value = ((List<T[]>)list)[row][column];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, column }, value, line, null, indexSources);
            return value;
        }

        public static T ArrayRead<T>(IList<T[]> list, int row, int column, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            T value = list[row][column];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, column }, value, line, null, indexSources);
            return value;
        }

        public static T ArrayRead<T>(IList<T>[] array, int row, int column, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            T value = array[row][column];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, column }, value, line, null, indexSources);
            return value;
        }

        public static T ArrayRead<T>(List<List<T>> list, int row, int column, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            T value = list[row][column];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, column }, value, line, null, indexSources);
            return value;
        }

        public static T ArrayRead<T>(IList<IList<T>> list, int row, int column, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            T value = list[row][column];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, column }, value, line, null, indexSources);
            return value;
        }

        public static TValue ArrayRead<TKey, TValue>(
            IList<Dictionary<TKey, TValue>> list,
            int row,
            TKey key,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            TValue value = list[row][key];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, key }, value, line, null, indexSources);
            return value;
        }

        public static TValue ArrayRead<TKey, TValue>(
            IList<TraceCodeDictionary<TKey, TValue>> list,
            int row,
            TKey key,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            TValue value = list[row][key];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, key }, value, line, null, indexSources);
            return value;
        }

        public static char ArrayRead(string text, int index, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            char value = text[index];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, index, value, line, null, indexSources);
            return value;
        }

        public static char ArrayRead(StringBuilder text, int index, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            char value = text[index];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, index, value, line, null, indexSources);
            return value;
        }

        public static char ArrayRead(IList<string> list, int row, int column, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            char value = list[row][column];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, column }, value, line, null, indexSources);
            return value;
        }

        public static char ArrayRead(string[] array, int row, int column, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            char value = array[row][column];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, column }, value, line, null, indexSources);
            return value;
        }

        public static TValue ArrayRead<TKey, TValue>(
            Dictionary<TKey, TValue>[] array,
            int row,
            TKey key,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            TValue value = array[row][key];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, key }, value, line, null, indexSources);
            return value;
        }

        public static TValue ArrayRead<TKey, TValue>(
            TraceCodeDictionary<TKey, TValue>[] array,
            int row,
            TKey key,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            TValue value = array[row][key];
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, new object?[] { row, key }, value, line, null, indexSources);
            return value;
        }

        public static void ArrayWrite<T>(T[] array, int index, T value, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            array[index] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, index, value, line, indexSources);
        }

        public static void ArrayWrite(char[] array, int index, int value, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            char charValue = (char)value;
            array[index] = charValue;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, index, charValue, line, indexSources);
        }

        public static void ArrayWrite(StringBuilder text, int index, char value, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            text[index] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, index, value, line, indexSources);
        }

        public static void ArrayWrite(StringBuilder text, int index, int value, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            char charValue = (char)value;
            text[index] = charValue;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, index, charValue, line, indexSources);
        }

        public static void ArrayWrite<T>(IList<T> list, int index, T value, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            list[index] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, index, value, line, indexSources);
        }

        public static void ArrayWrite<TKey, TValue>(
            IDictionary<TKey, TValue> dictionary,
            TKey key,
            TValue value,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            dictionary[key] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, key, value, line, indexSources);
        }

        public static void ArrayWrite<TKey, TValue>(
            IDictionary<TKey, TValue[]> dictionary,
            TKey key,
            int index,
            TValue value,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            dictionary[key][index] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { key, index }, value, line, indexSources);
        }

        public static void ArrayWrite<TKey, TValue>(
            IDictionary<TKey, List<TValue>> dictionary,
            TKey key,
            int index,
            TValue value,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            dictionary[key][index] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { key, index }, value, line, indexSources);
        }

        public static void ArrayWrite<TKey, TValue>(
            IDictionary<TKey, TraceCodeList<TValue>> dictionary,
            TKey key,
            int index,
            TValue value,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            dictionary[key][index] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { key, index }, value, line, indexSources);
        }

        public static void ArrayWrite<T>(T[][] array, int row, int column, T value, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            array[row][column] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { row, column }, value, line, indexSources);
        }

        public static void ArrayWrite<T>(T[,] array, int row, int column, T value, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            array[row, column] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { row, column }, value, line, indexSources);
        }

        public static void ArrayWrite<T>(T[,,] array, int first, int second, int third, T value, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            array[first, second, third] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { first, second, third }, value, line, indexSources);
        }

        public static void ArrayWrite<T>(IList<T[]> list, int row, int column, T value, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            list[row][column] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { row, column }, value, line, indexSources);
        }

        public static void ArrayWrite<T>(IList<T>[] array, int row, int column, T value, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            array[row][column] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { row, column }, value, line, indexSources);
        }

        public static void ArrayWrite<T>(List<List<T>> list, int row, int column, T value, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            list[row][column] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { row, column }, value, line, indexSources);
        }

        public static void ArrayWrite<T>(IList<IList<T>> list, int row, int column, T value, string variable, int line, IReadOnlyList<string?>? indexSources = null)
        {
            list[row][column] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { row, column }, value, line, indexSources);
        }

        public static void ArrayWrite<TKey, TValue>(
            IList<Dictionary<TKey, TValue>> list,
            int row,
            TKey key,
            TValue value,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            list[row][key] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { row, key }, value, line, indexSources);
        }

        public static void ArrayWrite<TKey, TValue>(
            IList<TraceCodeDictionary<TKey, TValue>> list,
            int row,
            TKey key,
            TValue value,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            list[row][key] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { row, key }, value, line, indexSources);
        }

        public static void ArrayWrite<TKey, TValue>(
            Dictionary<TKey, TValue>[] array,
            int row,
            TKey key,
            TValue value,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            array[row][key] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { row, key }, value, line, indexSources);
        }

        public static void ArrayWrite<TKey, TValue>(
            TraceCodeDictionary<TKey, TValue>[] array,
            int row,
            TKey key,
            TValue value,
            string variable,
            int line,
            IReadOnlyList<string?>? indexSources = null
        ) where TKey : notnull
        {
            array[row][key] = value;
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, new object?[] { row, key }, value, line, indexSources);
        }

        public static T FieldRead<T>(T value, string variable, string field, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.FieldRead(variable, field, value, line);
            return value;
        }

        public static T FieldRead<T>(T value, string variable, string[] path, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.FieldRead(variable, path, value, line);
            return value;
        }

        public static T FieldRead<T>(T value, string variable, object?[] path, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.FieldRead(variable, path, value, line);
            return value;
        }

        public static T FieldRead<T>(T value, string variable, object?[] path, int line, IReadOnlyList<string?>? indexSources)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.FieldRead(variable, path, value, line, indexSources);
            return value;
        }

        public static T FieldWrite<T>(T value, string variable, string field, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.FieldWrite(variable, field, value, line);
            return value;
        }

        public static T FieldWrite<T>(T value, string variable, string[] path, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.FieldWrite(variable, path, value, line);
            return value;
        }

        public static T FieldWrite<T>(T value, string variable, object?[] path, int line)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.FieldWrite(variable, path, value, line);
            return value;
        }

        public static T FieldWrite<T>(T value, string variable, object?[] path, int line, IReadOnlyList<string?>? indexSources)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.FieldWrite(variable, path, value, line, indexSources);
            return value;
        }

        public static void CheckTimeout()
        {
            TraceCode.CSharpHost.RuntimeTraceSink.CheckTimeout();
        }

        public static void WithVariableAlias(string actualVariable, string sourceVariable, Action action)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.WithVariableAlias(actualVariable, sourceVariable, action);
        }

        public static T WithVariableAlias<T>(string actualVariable, string sourceVariable, Func<T> action)
        {
            return TraceCode.CSharpHost.RuntimeTraceSink.WithVariableAlias(actualVariable, sourceVariable, action);
        }

        public static T WithIndexSources<T>(IReadOnlyList<string?>? indexSources, Func<T> action)
        {
            return TraceCode.CSharpHost.RuntimeTraceSink.WithIndexSources(indexSources, action);
        }

        public static void WithIndexSources(IReadOnlyList<string?>? indexSources, Action action)
        {
            TraceCode.CSharpHost.RuntimeTraceSink.WithIndexSources(indexSources, action);
        }

        public static bool DictionaryTryGetValue<TKey, TValue>(
            TraceCodeDictionary<TKey, TValue> dictionary,
            TKey key,
            out TValue value,
            int line,
            IReadOnlyList<string?>? indexSources)
            where TKey : notnull
        {
            return dictionary.TryGetValue(key, out value, line, indexSources);
        }
    }

    public sealed class TraceCodeList<T> : List<T>
    {
        private readonly string variable;

        public TraceCodeList(string variable, int line)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeList(string variable, int line, int capacity)
            : base(capacity)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeList(string variable, int line, IEnumerable<T> collection)
            : base(collection)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new T this[int index]
        {
            get
            {
                T value = base[index];
                TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, index, value, TraceCode.CSharpHost.RuntimeTraceSink.CurrentLine, null, TraceCode.CSharpHost.RuntimeTraceSink.CurrentScopedIndexSources);
                return value;
            }
            set
            {
                base[index] = value;
                TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, index, value, TraceCode.CSharpHost.RuntimeTraceSink.CurrentLine, TraceCode.CSharpHost.RuntimeTraceSink.CurrentScopedIndexSources);
                TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
            }
        }

        public new void Add(T item)
        {
            int index = Count;
            base.Add(item);
            int line = TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine;
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Add", new object?[] { item }, line);
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, index, item, line);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new void RemoveAt(int index)
        {
            base.RemoveAt(index);
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "RemoveAt", new object?[] { index }, TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new void Clear()
        {
            base.Clear();
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Clear", Array.Empty<object?>(), TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new void Sort()
        {
            base.Sort();
            EmitSortMutation(Array.Empty<object?>());
        }

        public new void Sort(Comparison<T> comparison)
        {
            base.Sort(comparison);
            EmitSortMutation(new object?[] { "<comparison>" });
        }

        public new void Sort(IComparer<T>? comparer)
        {
            base.Sort(comparer);
            EmitSortMutation(new object?[] { "<comparer>" });
        }

        public new void Sort(int index, int count, IComparer<T>? comparer)
        {
            base.Sort(index, count, comparer);
            EmitSortMutation(new object?[] { index, count, "<comparer>" });
        }

        private void EmitSortMutation(IReadOnlyList<object?> args)
        {
            int line = TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine;
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Sort", args, line);
            int limit = TraceCode.CSharpHost.RuntimeTraceSink.BulkIndexedWriteLimit(Count);
            for (int index = 0; index < limit; index += 1)
            {
                TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, index, base[index], line);
            }
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }
    }

    public sealed class TraceCodeDictionary<TKey, TValue> : Dictionary<TKey, TValue>
        where TKey : notnull
    {
        private readonly string variable;

        public TraceCodeDictionary(string variable, int line)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeDictionary(string variable, int line, int capacity)
            : base(capacity)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeDictionary(string variable, int line, IEqualityComparer<TKey>? comparer)
            : base(comparer)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeDictionary(string variable, int line, int capacity, IEqualityComparer<TKey>? comparer)
            : base(capacity, comparer)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeDictionary(string variable, int line, IDictionary<TKey, TValue> dictionary)
            : base(dictionary)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeDictionary(string variable, int line, IDictionary<TKey, TValue> dictionary, IEqualityComparer<TKey>? comparer)
            : base(dictionary, comparer)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeDictionary(string variable, int line, IEnumerable<KeyValuePair<TKey, TValue>> collection)
            : base(collection)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeDictionary(
            string variable,
            int line,
            IEnumerable<KeyValuePair<TKey, TValue>> collection,
            IEqualityComparer<TKey>? comparer)
            : base(collection, comparer)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new TValue this[TKey key]
        {
            get
            {
                TValue value = base[key];
                TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, key, value, TraceCode.CSharpHost.RuntimeTraceSink.CurrentLine, null, TraceCode.CSharpHost.RuntimeTraceSink.CurrentScopedIndexSources);
                return value;
            }
            set
            {
                base[key] = value;
                TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, key, value, TraceCode.CSharpHost.RuntimeTraceSink.CurrentLine, TraceCode.CSharpHost.RuntimeTraceSink.CurrentScopedIndexSources);
                TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
            }
        }

        public new void Add(TKey key, TValue value)
        {
            base.Add(key, value);
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Add", new object?[] { key, value }, TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new bool Remove(TKey key)
        {
            bool removed = base.Remove(key);
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(
                variable,
                new object?[] { key },
                "Remove",
                new object?[] { key },
                TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine,
                TraceCode.CSharpHost.RuntimeTraceSink.CurrentScopedIndexSources);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
            return removed;
        }

        public new void Clear()
        {
            base.Clear();
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Clear", Array.Empty<object?>(), TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new bool ContainsKey(TKey key)
        {
            return base.ContainsKey(key);
        }

        public new bool TryGetValue(TKey key, out TValue value)
        {
            return TryGetValue(key, out value, TraceCode.CSharpHost.RuntimeTraceSink.CurrentLine, TraceCode.CSharpHost.RuntimeTraceSink.CurrentScopedIndexSources);
        }

        public bool TryGetValue(TKey key, out TValue value, int line, IReadOnlyList<string?>? indexSources)
        {
            bool found = base.TryGetValue(key, out value!);
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, key, found ? value : default, line, null, indexSources);
            return found;
        }
    }

    public sealed class TraceCodeHashSet<T> : HashSet<T>
    {
        private readonly string variable;

        public TraceCodeHashSet(string variable, int line)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeHashSet(string variable, int line, int capacity)
            : base(capacity)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeHashSet(string variable, int line, IEqualityComparer<T>? comparer)
            : base(comparer)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeHashSet(string variable, int line, int capacity, IEqualityComparer<T>? comparer)
            : base(capacity, comparer)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeHashSet(string variable, int line, IEnumerable<T> collection)
            : base(collection)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeHashSet(string variable, int line, IEnumerable<T> collection, IEqualityComparer<T>? comparer)
            : base(collection, comparer)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new bool Add(T item)
        {
            bool added = base.Add(item);
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Add", new object?[] { item }, TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
            return added;
        }

        public new bool Contains(T item)
        {
            bool contains = base.Contains(item);
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, item!, contains, TraceCode.CSharpHost.RuntimeTraceSink.CurrentLine);
            return contains;
        }

        public new bool Remove(T item)
        {
            bool removed = base.Remove(item);
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(
                variable,
                new object?[] { item },
                "Remove",
                new object?[] { item },
                TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine,
                TraceCode.CSharpHost.RuntimeTraceSink.CurrentScopedIndexSources);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
            return removed;
        }

        public new void Clear()
        {
            base.Clear();
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Clear", Array.Empty<object?>(), TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }
    }

    public sealed class TraceCodeQueue<T> : Queue<T>
    {
        private readonly string variable;

        public TraceCodeQueue(string variable, int line)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeQueue(string variable, int line, int capacity)
            : base(capacity)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeQueue(string variable, int line, IEnumerable<T> collection)
            : base(collection)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new void Enqueue(T item)
        {
            base.Enqueue(item);
            int line = TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine;
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Enqueue", new object?[] { item }, line);
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, Count - 1, item, line);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new T Dequeue()
        {
            T item = base.Dequeue();
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Dequeue", Array.Empty<object?>(), TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
            return item;
        }

        public new T Peek()
        {
            T item = base.Peek();
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, 0, item, TraceCode.CSharpHost.RuntimeTraceSink.CurrentLine);
            return item;
        }
    }

    public sealed class TraceCodePriorityQueue<TElement, TPriority> : PriorityQueue<TElement, TPriority>
    {
        private readonly string variable;

        public TraceCodePriorityQueue(string variable, int line)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodePriorityQueue(string variable, int line, IComparer<TPriority>? comparer)
            : base(comparer)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodePriorityQueue(string variable, int line, int initialCapacity)
            : base(initialCapacity)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodePriorityQueue(string variable, int line, int initialCapacity, IComparer<TPriority>? comparer)
            : base(initialCapacity, comparer)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodePriorityQueue(string variable, int line, IEnumerable<(TElement Element, TPriority Priority)> items)
            : base(items)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodePriorityQueue(
            string variable,
            int line,
            IEnumerable<(TElement Element, TPriority Priority)> items,
            IComparer<TPriority>? comparer)
            : base(items, comparer)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new void Enqueue(TElement element, TPriority priority)
        {
            base.Enqueue(element, priority);
            int line = TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine;
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Enqueue", new object?[] { element }, line);
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedPriorityQueueWrites(variable, this, line);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new TElement Dequeue()
        {
            TElement item = base.Dequeue();
            int line = TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine;
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Dequeue", Array.Empty<object?>(), line);
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedPriorityQueueWrites(variable, this, line);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
            return item;
        }

        public new TElement Peek()
        {
            TElement item = base.Peek();
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, 0, item, TraceCode.CSharpHost.RuntimeTraceSink.CurrentLine);
            return item;
        }
    }

    public sealed class TraceCodeLinkedList<T> : LinkedList<T>
    {
        private readonly string variable;

        public TraceCodeLinkedList(string variable, int line)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeLinkedList(string variable, int line, IEnumerable<T> collection)
            : base(collection)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new LinkedListNode<T> AddLast(T value)
        {
            LinkedListNode<T> node = base.AddLast(value);
            int line = TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine;
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "append", new object?[] { value }, line);
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, Count - 1, value, line);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
            return node;
        }

        public new LinkedListNode<T> AddFirst(T value)
        {
            LinkedListNode<T> node = base.AddFirst(value);
            int line = TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine;
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "appendleft", new object?[] { value }, line);
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedWrite(variable, 0, value, line);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
            return node;
        }

        public new void RemoveFirst()
        {
            base.RemoveFirst();
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "popleft", Array.Empty<object?>(), TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new void RemoveLast()
        {
            base.RemoveLast();
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "pop", Array.Empty<object?>(), TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }
    }

    public sealed class TraceCodeStack<T> : Stack<T>
    {
        private readonly string variable;

        public TraceCodeStack(string variable, int line)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeStack(string variable, int line, int capacity)
            : base(capacity)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public TraceCodeStack(string variable, int line, IEnumerable<T> collection)
            : base(collection)
        {
            this.variable = variable;
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new void Push(T item)
        {
            base.Push(item);
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Push", new object?[] { item }, TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
        }

        public new T Pop()
        {
            T item = base.Pop();
            TraceCode.CSharpHost.RuntimeTraceSink.Mutate(variable, "Pop", Array.Empty<object?>(), TraceCode.CSharpHost.RuntimeTraceSink.ScopedSourceLine);
            TraceCode.CSharpHost.RuntimeTraceSink.Snapshot(variable, this);
            return item;
        }

        public new T Peek()
        {
            T item = base.Peek();
            TraceCode.CSharpHost.RuntimeTraceSink.IndexedRead(variable, 0, item, TraceCode.CSharpHost.RuntimeTraceSink.CurrentLine);
            return item;
        }
    }
}
