// Generated by scripts/generate-runtime-assets-lock.mjs. Do not edit.
export const TRACECC_RUNTIME_CONTENT_HASH = "fb4b6f41f9e9b7db89b6c8425bb2c6218979219a4150f96619b6461b4b78d294";
export const TRACECC_RUNTIME_ASSETS = Object.freeze({
  "runtimeHeader": {
    "fileName": "tracecode_runtime.hpp",
    "integrity": "sha256-WEbB8mLN8cwKIWPf25UL7yoTSM9nCqWs8MkE0B14EtE=",
    "mediaType": "text/plain",
    "size": 263083
  },
  "compilerWasm": {
    "fileName": "tracecc-reactor.wasm",
    "integrity": "sha256-At40hCU4Rmvynp1s8UzQ1eX/UZybo5BWHMsVgQXUTUE=",
    "mediaType": "application/wasm",
    "size": 33478188
  },
  "sysroot": {
    "fileName": "llvm-resources.tar",
    "integrity": "sha256-2V0qK8hAihbAdEmWrEfJG7PGO7cblDFcl5YIm23ahVU=",
    "mediaType": "application/x-tar",
    "size": 29112320
  },
  "narrowPch": {
    "fileName": "narrow.pch",
    "integrity": "sha256-rbuVm7YeO+HwDpSJPAqGGNrrPKeJveazS/juUWXs5/A=",
    "mediaType": "application/octet-stream",
    "size": 21322216
  },
  "narrowPchSource": {
    "fileName": "narrow.source.hpp",
    "integrity": "sha256-SMqxQfcMBSUHUcAz+7Cp4vkWyOtgv7mNB09JE1cOEAU=",
    "mediaType": "text/plain",
    "size": 815
  },
  "narrowRuntimeObject": {
    "fileName": "narrow.o",
    "integrity": "sha256-il/wX66FvAU9SJSiDepMuEZ00CipED4EEEfqcdxEg8c=",
    "mediaType": "application/wasm",
    "size": 1042570
  },
  "broadPch": {
    "fileName": "broad.pch",
    "integrity": "sha256-ktKxBSglo50GPM9GJJwBpqyYDcFHkKGjoyEtsUmLMrI=",
    "mediaType": "application/octet-stream",
    "size": 24543552
  },
  "broadPchSource": {
    "fileName": "broad.source.hpp",
    "integrity": "sha256-MOayycWl5KYaLS8vP2MoJh4kazsDhg0kH9Bi6dvsy0s=",
    "mediaType": "text/plain",
    "size": 7095
  },
  "broadRuntimeObject": {
    "fileName": "broad.o",
    "integrity": "sha256-f69Oe7kRn9JEIUEPgM1cuYbf50oph4IxEnVP7VIZGp4=",
    "mediaType": "application/wasm",
    "size": 1892879
  },
  "mapPch": {
    "fileName": "map.pch",
    "integrity": "sha256-fX7zTmJXnRJ2acbDiJ4Wu7/xf1G510SB2fLzkTgr2Uc=",
    "mediaType": "application/octet-stream",
    "size": 29951380
  },
  "mapPchSource": {
    "fileName": "map.source.hpp",
    "integrity": "sha256-WHaMpx3nG/h1ro6CppBseoDIkgqahbYnFxShHLGT9/c=",
    "mediaType": "text/plain",
    "size": 10708
  },
  "mapRuntimeObject": {
    "fileName": "map.o",
    "integrity": "sha256-02ktvX6uqV05it5kdBEm/ncOszBeO43wX93Yk079E4U=",
    "mediaType": "application/wasm",
    "size": 3372458
  }
} as const);
