/**
 * Compatibility facade for the 0.13 project workspace package.
 *
 * TraceKernel owns the implementation in 0.14. Keep this entrypoint broad
 * enough for existing consumers without transferring the legacy core
 * re-export surface into TraceKernel itself.
 */
export {
  RuntimeProjectWorkspace,
  createRuntimeWorkspace,
  JustBashRuntimeWorkspace,
  RuntimeProjectWorkspaceTerminalSession,
  createPackageManagerProjectCommands,
  syntheticIp,
  syntheticLatency,
  RUNTIME_WORKSPACE_DEFAULT_MAX_BYTES,
  RUNTIME_WORKSPACE_DEFAULT_MAX_ENTRY_COUNT,
  RUNTIME_WORKSPACE_DEFAULT_MAX_FILE_BYTES,
  normalizeRuntimeWorkspaceStorageLimits,
  createPythonProjectCommands,
  createNodeProjectCommands,
  createTypeScriptProjectCommands,
  createJavaProjectCommands,
  createCppProjectCommands,
  createCSharpProjectCommands,
  type HostResolution,
  type NormalizedRuntimeWorkspaceStorageLimits,
  type RuntimeWorkspaceStorageLimits,
  type CppProjectCommandRequest,
  type CppProjectCommandRunner,
  type CreateRuntimeWorkspaceOptions,
  type CSharpProjectCommandRequest,
  type CSharpProjectCommandRunner,
  type JavaProjectCommandRequest,
  type JavaProjectCommandRunner,
  type JavaScriptProjectCommandRequest,
  type JavaScriptProjectCommandRunner,
  type ProjectWorkspaceCommand,
  type ProjectWorkspaceExecutionLimits,
  type ProjectWorkspaceJavaScriptConfig,
  type PythonProjectCommandRequest,
  type PythonProjectCommandRunner,
  type RuntimePackageDependencyProvider,
  type RuntimePackageInstallRequest,
  type RuntimePackageManagerConfig,
  type RuntimePackageManagerName,
  type RuntimePackageManifest,
  type RuntimeTraceKernelControlOptions,
  type TypeScriptProjectCommandRequest,
  type TypeScriptProjectCommandRunner,
} from '@tracecode/tracekernel/workspace';

export {
  RuntimeProjectLiveIoController,
  createRuntimeProjectHiddenCommandAccess,
  createRuntimeProjectIoBridge,
  createDefaultExternalHttpFetch,
  isBlockedExternalHttpHost,
  RUNTIME_EXTERNAL_HTTP_MAX_BODY_BYTES,
  runRuntimeProjectWorkerBridge,
  runtimeHttpBodyBytes,
  runtimeHttpBodyFromBytes,
  runtimeHttpBodyFromText,
  runtimeHttpBodyText,
  runtimeHttpRequestBytes,
  runtimeHttpRequestText,
  runtimeHttpResponseBytes,
  runtimeHttpResponseText,
  normalizeRuntimeProjectPath,
} from '@tracecode/harness-core';

export type {
  RuntimeCommandOptions,
  RuntimeCommandResult,
  RuntimeCommandEvent,
  RuntimeCommandEventHandler,
  RuntimeCommandEventStream,
  RuntimeCommandFileChangeEvent,
  RuntimeCommandOutputEvent,
  RuntimeCommandStatusEvent,
  KernelJournalRecord,
  RuntimeFile,
  RuntimeFileChange,
  RuntimeFileDeletion,
  RuntimeSymlink,
  RuntimeDirectory,
  RuntimeDirectoryChange,
  RuntimeFileEncoding,
  RuntimeKernelHostConfig,
  RuntimeKernelHostInfo,
  RuntimeKernelInfo,
  RuntimeKernelHttpBridge,
  RuntimeKernelHttpBodyInit,
  RuntimeKernelHttpBodyPayload,
  RuntimeKernelHttpError,
  RuntimeKernelHttpHandler,
  RuntimeKernelHttpListenOptions,
  RuntimeKernelHttpListenerHandle,
  RuntimeKernelHttpListenerInfo,
  RuntimeKernelHttpRequest,
  RuntimeKernelHttpResponse,
  RuntimeKernelUserConfig,
  RuntimeKernelUserInfo,
  RuntimeKernelWorkspaceConfig,
  RuntimeKernelWorkspaceInfo,
  RuntimeTraceKernelSchedulerConfig,
  RuntimeKernelDevicePath,
  RuntimeFileMutationPhase,
  RuntimeTraceKernelConfig,
  RuntimeProjectCommandRequest,
  RuntimeProjectCommandRunner,
  RuntimeProjectTerminalPrompt,
  RuntimeProjectTerminalEvent,
  RuntimeProjectTerminalEventHandler,
  RuntimeProjectTerminalInputState,
  RuntimeProjectTerminalInputStateReason,
  RuntimeProjectTerminalRunOptions,
  RuntimeProjectTerminalSession,
  RuntimeProjectTerminalSessionOptions,
  RuntimeProjectSession,
  RuntimeProjectSessionCommand,
  RuntimeProjectSessionCommandDefinition,
  RuntimeProjectSessionFile,
  RuntimeProjectSessionInfo,
  RuntimeProjectIoBridge,
  RuntimeProjectPatch,
  RuntimeProjectPatchBase,
  RuntimeProjectPatchChange,
  RuntimeProjectPatchDirectoryCreate,
  RuntimeProjectPatchDirectoryWrite,
  RuntimeProjectPatchDirectoryDelete,
  RuntimeProjectPatchFileDelete,
  RuntimeProjectPatchFileWrite,
  RuntimeProjectPatchSymlinkWrite,
  RuntimeProjectPatchOptions,
  RuntimeProjectLiveIoControllerOptions,
  RuntimeProjectWorkerBridgeOptions,
  RuntimeProjectSnapshot,
  RuntimeWorkspace,
  RuntimeWorkspaceActor,
  RuntimeWorkspaceActorKind,
  RuntimeWorkspaceCapabilities,
  RuntimeWorkspaceEvent,
  RuntimeWorkspaceEventHandler,
  RuntimeWorkspaceHttpClient,
  RuntimeWorkspaceHttpJsonRequestOptions,
  RuntimeWorkspaceHttpJsonResponse,
  RuntimeWorkspaceHttpRequestOptions,
  RuntimeWorkspaceKernel,
  RuntimeWorkspaceProcess,
  RuntimeWorkspaceProcessOptions,
  RuntimeWorkspaceProcessSignalPolicy,
  RuntimeWorkspaceRemoveOptions,
  RuntimeWorkspaceStat,
  RuntimeWorkspaceUnsubscribe,
  RuntimeExternalHttpConfig,
  RuntimeExternalHttpRequest,
} from '@tracecode/harness-core';
