// Generated by scripts/generate-runtime-assets-lock.mjs. Do not edit.
export const TRACEJVM_RUNTIME_VERSION = "0.4.1";
export const TRACEJVM_RUNTIME_CONTENT_HASH = "a954d0ad32ff8c62e765847a65081a39a7ad33da0b9617cb8ddbd46082d6247a";
export const TRACEJVM_RUNTIME_ASSET_RELATIVE_PATH = "java/tracejvm/0.4.1/a954d0ad32ff8c62e765847a65081a39a7ad33da0b9617cb8ddbd46082d6247a";
export const TRACEJVM_RUNTIME_RELEASE_DESCRIPTOR = Object.freeze({
  "integrity": "sha256-9x4v5tbwHkoMG+iwh/ufWN1C0PKQpNEHOvuAzb5bmBY=",
  "size": 121712
} as const);
