// Generated by scripts/generate-runtime-assets-lock.mjs. Do not edit.
export const TRACEJVM_RUNTIME_VERSION = "0.4.1";
export const TRACEJVM_RUNTIME_CONTENT_HASH = "446bd4e38f2abcb497c8b52954e791ced91f694c21ecf992db990597e9b21dd8";
export const TRACEJVM_RUNTIME_ASSET_RELATIVE_PATH = "java/tracejvm/0.4.1/446bd4e38f2abcb497c8b52954e791ced91f694c21ecf992db990597e9b21dd8";
export const TRACEJVM_RUNTIME_RELEASE_DESCRIPTOR = Object.freeze({
  "integrity": "sha256-8cQEJgraoqMtJDsRGzYzlj4vmxLDuEVjz9uePVY+oNs=",
  "size": 189839
} as const);
