// Generated by scripts/generate-runtime-assets-lock.mjs. Do not edit.
export const TRACEJVM_RUNTIME_VERSION = "0.4.1";
export const TRACEJVM_RUNTIME_CONTENT_HASH = "8a8142393d439eaf28c09c66b4f47c411faf4b7b10c0cfe029e859129112654e";
export const TRACEJVM_RUNTIME_ASSET_RELATIVE_PATH = "java/tracejvm/0.4.1/8a8142393d439eaf28c09c66b4f47c411faf4b7b10c0cfe029e859129112654e";
export const TRACEJVM_RUNTIME_RELEASE_DESCRIPTOR = Object.freeze({
  "integrity": "sha256-l57StxPy2eUzbs0QgBaY6sMOj2QFGk2mtcv7g2iO/DA=",
  "size": 121714
} as const);
