// Generated by scripts/generate-runtime-assets-lock.mjs. Do not edit.
export const PYTHON_RUNTIME_DIRECTORY = "python/pyodide-0.29.3";
export const PYTHON_RUNTIME_WASM = Object.freeze({
  "integrity": "sha256-4vTudbMl416zG/uMYT1N1QmPVQLBVql4R2hodbUCVIA=",
  "size": 8647684
} as const);
export const PYTHON_RUNTIME_SNAPSHOTS = Object.freeze({
  "chromium": {
    "integrity": "sha256-9uWlkAbBhlbRC1kWgf5r0Am30Thew5WjsAgNMzu7gVE=",
    "size": 20971936
  },
  "firefox": {
    "integrity": "sha256-ozSkcg1128ksIGL0HrfKsqHNmBknSK0J9D/RulzOO6k=",
    "size": 20971936
  },
  "webkit": {
    "integrity": "sha256-CgYZCcL24qPIweRqLooHHsXYv7RgbEfJm5UydYNoqRc=",
    "size": 20971936
  }
} as const);
