/**
 * Public browser Judge authority.
 *
 * Runtime provider registration and the browser runtime host are implementation
 * details. Consumers own one BrowserJudgeHost, optionally warm a selected
 * language, and create scoped Judge evaluations through that authority.
 */
export {
  createBrowserProjectJudge,
  createBrowserJudgeHost,
  evaluateJudgePlan,
  structuralJsonComparator,
} from './internal/browser-judge';

export type {
  BrowserJudgeCppOptions,
  BrowserJudgeCSharpOptions,
  BrowserJudgeExecutionHostOptions,
  BrowserJudgeHost,
  BrowserJudgeJavaOptions,
  BrowserJudgePythonOptions,
  BrowserProjectJudge,
  BrowserProjectJudgeWorkspaceOptions,
  CreateBrowserJudgeHostOptions,
  CreateBrowserJudgeOptions,
  CreateBrowserProjectJudgeOptions,
  JudgeCasePlan,
  JudgeCaseResult,
  JudgeCaseVerdict,
  JudgeComparator,
  JudgeComparisonInput,
  JudgeComparisonResult,
  JudgeDiagnostic,
  JudgeEvaluationOptions,
  JudgeEvaluationPlan,
  JudgeEvaluationResult,
  JudgeProcessPlan,
  JudgeRuntimeControlPort,
  JudgeRuntimeInvocationInput,
  JudgeRuntimeInvocationOutput,
  JudgeWorkspaceFile,
  RuntimeJudge,
  RuntimeJudgeBinding,
  RuntimeJudgeCodeBinding,
  RuntimeJudgeTraceBinding,
} from './internal/browser-judge';

export {
  PROJECT_ATTEMPT_SCHEMA,
  PROJECT_BUNDLE_SCHEMA,
  PROJECT_DEFINITION_SCHEMA,
  PROJECT_EXECUTION_EVIDENCE_SCHEMA,
  PROJECT_RECEIPT_SCHEMA,
  behaviorProjectEvaluatorV1,
  builtInProjectEvaluators,
  debuggingProjectEvaluatorV1,
  evaluateJudgeVerdictPolicy,
  evaluateProjectJudgeBundle,
  evaluateProjectJudgeEvidenceBundle,
  evaluateProjectJudgeEvidenceBundlePromise,
  evaluateProjectJudgeEvidenceBundleSync,
  judgeFactMeetsRequirement,
  validateProjectJudgeBundle,
} from '../packages/judge/src/index';

export {
  ALGORITHM_BUNDLE_SCHEMA,
  ALGORITHM_RECEIPT_SCHEMA,
  algorithmSourcePath,
  algorithmWorkspaceDigest,
  allCasesPassPolicy,
  compareJudgeValues,
  createAlgorithmJudgeBundle,
  createAlgorithmJudgeReceipt,
  createJudgeComparator,
  runJudgeCustomValidator,
} from '../packages/judge/src/index';

export type {
  JudgeAlgorithmBundle,
  JudgeAlgorithmLanguage,
  JudgeAlgorithmSourceCase,
  JudgeAlgorithmEvaluationOptions,
  JudgeAlgorithmReceipt,
  JudgeAlgorithmVerdict,
  JudgeComparatorStrategy,
  JudgeComparatorPolicy,
  JudgeCompareMode,
  JudgeCustomValidatorId,
  CreateAlgorithmJudgeBundleOptions,
  UnboundJudgeFact,
} from '../packages/judge/src/index';

export type {
  JudgeArtifactRef,
  JudgeExecutionStatus,
  JudgeFact,
  JudgeFactRequirement,
  JudgeFactSubject,
  JudgeFactVerification,
  JudgePolicyEvaluation,
  JudgeValueExpression,
  JudgeProjectAttemptV1,
  JudgeProjectBundleV1,
  JudgeProjectClaim,
  JudgeProjectClaimStatus,
  JudgeProjectCommandStep,
  JudgeProjectCommandStepReceipt,
  JudgeProjectDefinitionV1,
  JudgeProjectEvaluationOptions,
  JudgeProjectEvaluator,
  JudgeProjectEvaluatorReference,
  JudgeProjectExecutionEvidenceV1,
  JudgeProjectReceiptV1,
  JudgeProjectResultV1,
  JudgeProjectServiceProbeStep,
  JudgeProjectServiceProbeStepReceipt,
  JudgeProjectStep,
  JudgeProjectStepReceipt,
  JudgeProjectWorkspaceView,
  JudgeWeightedScoreDimension,
  JudgeWeightedScorePolicy,
  JudgeTechnicalVerdict,
  JudgeTruth,
  JudgeVerdictPolicy,
  JudgeBooleanExpression,
  JudgeObservation,
  JudgeProcessResult,
} from '../packages/judge/src/index';
