/**
 * Public TraceKernel surface.
 *
 * TraceKernel owns interactive execution: the kernel itself, its workspace
 * model, browser persistence, browser execution-host plumbing, and the
 * browser workspace factory that assembles the installed language runtimes.
 * Language workers and provider registries remain private implementation
 * details.
 */
export * from '@tracecode/tracekernel';
export * from '@tracecode/tracekernel/workspace';

export {
  createBrowserProjectWorkspace as createBrowserWorkspace,
  createIndexedDbKernelStorage,
  createBrowserExecutionWorkerHost,
  installBrowserExecutionWorkerHost,
  runtimeHttpBodyBytes,
  runtimeHttpBodyFromBytes,
  runtimeHttpBodyFromText,
  runtimeHttpBodyText,
  runtimeHttpRequestBytes,
  runtimeHttpRequestText,
  runtimeHttpResponseBytes,
  runtimeHttpResponseText,
  type BrowserKernelStorage,
  type BrowserKernelStorageBinding,
  type BrowserKernelStorageSnapshot,
  type BrowserProjectExecutionHostOptions as BrowserWorkspaceExecutionHostOptions,
  type BrowserProjectJavaRuntimeOptions as BrowserWorkspaceJavaRuntimeOptions,
  type BrowserProjectNodeOptions as BrowserWorkspaceNodeOptions,
  type BrowserProjectProvider as BrowserWorkspaceProvider,
  type BrowserProjectRuntimeProvider as BrowserWorkspaceRuntimeProvider,
  type BrowserProjectRuntimeProviders as BrowserWorkspaceRuntimeProviders,
  type BrowserProjectTypeScriptOptions as BrowserWorkspaceTypeScriptOptions,
  type BrowserProjectWorkerIsolation as BrowserWorkspaceWorkerIsolation,
  type BrowserProjectWorkerPrewarmOptions as BrowserWorkspaceWorkerPrewarmOptions,
  type BrowserProjectWorkspace as BrowserWorkspace,
  type CreateBrowserProjectWorkspaceOptions as CreateBrowserWorkspaceOptions,
  type IndexedDbKernelStorageOptions,
  type InstallBrowserExecutionWorkerHostOptions,
} from '../packages/runtime-browser/src/project';

export {
  BROWSER_RUNTIME_ASSET_PROTOCOL_VERSION,
  BROWSER_RUNTIME_IDS,
  resolveBrowserRuntimeAssets,
  resolveBrowserRuntimeAssetManifests,
  type AnyBrowserRuntimeAssetManifest,
  type BrowserRuntimeAssetDelivery,
  type BrowserRuntimeAssetDescriptor,
  type BrowserRuntimeAssetManifest,
  type BrowserRuntimeAssetManifestProvider,
  type BrowserRuntimeAssetManifests,
  type BrowserRuntimeAssetOriginPolicy,
  type BrowserRuntimeAssetOverrides,
  type BrowserRuntimeAssets,
  type BrowserRuntimeAssetsByRuntime,
  type BrowserRuntimeId,
  type BrowserRuntimeLoaderFormat,
  type BrowserRuntimeWorkerFormat,
  type CppCompilerIntegrityEntry,
  type CppCompilerIntegrityManifest,
} from '../packages/runtime-browser/src/runtime-assets';

export {
  assertRuntimeRequestSupported,
} from '../packages/runtime-browser/src/runtime-capability-guards';

export {
  createPythonAnalysisClient,
  type CreatePythonAnalysisClientOptions,
  type PythonAnalysisClient,
} from './internal/python-analysis';

export {
  createBrowserRuntimeEnvironment,
  type BrowserRuntimeEngine,
  type BrowserRuntimeEnvironment,
  type BrowserRuntimeEnvironmentOptions,
  type BrowserRuntimeEnvironmentReport,
  type BrowserRuntimeFeatureSupport,
  type BrowserRuntimeKnownIssue,
  type BrowserRuntimeReadiness,
  type BrowserRuntimeReadinessStatus,
  type BrowserRuntimeSurface,
} from '../packages/runtime-browser/src/runtime-environment';

export {
  LANGUAGE_RUNTIME_PROFILES,
  SUPPORTED_LANGUAGES,
  getLanguageRuntimeProfile,
  getRuntimeProjectIoCapability,
  getRuntimeProjectIoCapabilityMatrix,
  getRuntimeProjectIoSupport,
  getSupportedLanguageProfiles,
  isLanguageSupported,
  isRuntimeSafeForUntrustedReuse,
} from '../packages/runtime-browser/src/runtime-profiles';

export {
  createEmptyRuntimeTrace,
} from '../packages/runtime-contracts/src/runtime-trace';

export {
  NODE_RUNTIME_COMPAT_VERSION,
  LANGUAGE_RUNTIME_INFOS,
  SUPPORTED_LANGUAGE_RUNTIME_INFOS,
  getLanguageRuntimeInfo,
  getSupportedLanguageRuntimeInfos,
  type LanguageRuntimeInfo,
  type RuntimeComponentInfo,
  type RuntimeLibraryInfo,
} from '../packages/runtime-contracts/src/runtime-language-info';

export type {
  CodeExecutionResult,
  ExecutionDiagnosticStage,
  ExecutionLimitReason,
  ExecutionResult,
  Language,
  LanguageRuntimeProfile,
  RuntimeCapabilities,
  RuntimeCommandEvent,
  RuntimeCommandEventHandler,
  RuntimeCommandEventStream,
  RuntimeCommandFileChangeEvent,
  RuntimeCommandOptions,
  RuntimeCommandOutputEvent,
  RuntimeCommandResult,
  RuntimeCommandStatusEvent,
  RuntimeCompileCost,
  RuntimeExecutionIsolationBoundary,
  RuntimeExecutionIsolationPolicy,
  RuntimeExecutionIsolationSupport,
  RuntimeExecutionLimitSupport,
  RuntimeExecutionLimits,
  RuntimeExecutionPipeline,
  RuntimeExecutionStyle,
  RuntimeExecuteCase,
  RuntimeExecuteCaseResult,
  RuntimeExecuteCodeRequest,
  RuntimeExecuteResult,
  RuntimeFile,
  RuntimeFileChange,
  RuntimeFileEncoding,
  RuntimeFileMutationPhase,
  RuntimeKernelDevicePath,
  RuntimeKernelHostConfig,
  RuntimeKernelHostInfo,
  RuntimeKernelHttpBodyInit,
  RuntimeKernelHttpBodyPayload,
  RuntimeKernelHttpBridge,
  RuntimeKernelHttpHandler,
  RuntimeKernelHttpListenOptions,
  RuntimeKernelHttpListenerHandle,
  RuntimeKernelHttpListenerInfo,
  RuntimeKernelHttpRequest,
  RuntimeKernelHttpResponse,
  RuntimeKernelInfo,
  RuntimeKernelUserConfig,
  RuntimeKernelUserInfo,
  RuntimeKernelWorkspaceConfig,
  RuntimeKernelWorkspaceInfo,
  RuntimeMaturity,
  RuntimeProjectCommandRequest,
  RuntimeProjectCommandRunner,
  RuntimeProjectIoBridge,
  RuntimeProjectIoCapabilityRow,
  RuntimeProjectIoEnvironment,
  RuntimeProjectIoSupport,
  RuntimeProjectIoTier,
  RuntimeProjectLiveIoControllerOptions,
  RuntimeProjectPatch,
  RuntimeProjectPatchBase,
  RuntimeProjectPatchChange,
  RuntimeProjectPatchDirectoryCreate,
  RuntimeProjectPatchDirectoryDelete,
  RuntimeProjectPatchFileDelete,
  RuntimeProjectPatchFileWrite,
  RuntimeProjectPatchOptions,
  RuntimeProjectSession,
  RuntimeProjectSessionCommand,
  RuntimeProjectSessionCommandDefinition,
  RuntimeProjectSessionFile,
  RuntimeProjectSessionInfo,
  RuntimeProjectSnapshot,
  RuntimeProjectTerminalEvent,
  RuntimeProjectTerminalEventHandler,
  RuntimeProjectTerminalInputState,
  RuntimeProjectTerminalInputStateReason,
  RuntimeProjectTerminalPrompt,
  RuntimeProjectTerminalRunOptions,
  RuntimeProjectTerminalSession,
  RuntimeProjectTerminalSessionOptions,
  RuntimeProjectWorkerBridgeOptions,
  RuntimeTraceKernelConfig,
  RuntimeTraceKernelSchedulerConfig,
  RuntimeTrace,
  RuntimeWorkspace,
  RuntimeWorkspaceActor,
  RuntimeWorkspaceActorKind,
  RuntimeWorkspaceCapabilities,
  RuntimeWorkspaceEvent,
  RuntimeWorkspaceEventHandler,
  RuntimeWorkspaceHttpClient,
  RuntimeWorkspaceHttpJsonRequestOptions,
  RuntimeWorkspaceHttpJsonResponse,
  RuntimeWorkspaceHttpRequestOptions,
  RuntimeWorkspaceKernel,
  RuntimeWorkspaceRemoveOptions,
  RuntimeWorkspaceStat,
  RuntimeWorkspaceUnsubscribe,
  TraceExecutionOptions,
} from '../packages/runtime-contracts/src/index';
